<a href="https://colab.research.google.com/github/Eisawi7/date-mining-1/blob/main/Welcome_to_Colaboratory.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. NumPy

In [1]:
# Creating an array
import numpy as np

arr = np.array([1, 2, 3 ,4, 5])
print(arr)

[1 2 3 4 5]


In [2]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Matrix opearation

In [3]:
transpose = matrix.T
print(transpose)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


statistics

In [4]:
print(arr)
mean = np.mean(arr)
print(mean)

[1 2 3 4 5]
3.0


In [5]:
std = np.std(arr)
print(std)

1.4142135623730951


In [7]:
sum = np.sum(arr)
print("the Sum of all element in the array is", sum)

the Sum of all element in the array is 15


In [ ]:
pandas

In [6]:
import pandas as pd

In [14]:
data={
    'Name':['Alice','Bob','Claire'],
    'Age':[25,30,27],
    'Gender':['Female','Male','Female']
}
print(df)

      Name  Age           City
0    Alice   25       New York
1      Bob   30  San Francisco
2  Charlie   35    Los Angeles


In [15]:
df.describe().T

count  mean  std   min   25%   50%   75%   max
Age    3.0  30.0  5.0  25.0  27.5  30.0  32.5  35.0

In [16]:
df.describe()

Age
count   3.0
mean   30.0
std     5.0
min    25.0
25%    27.5
50%    30.0
75%    32.5
max    35.0

dtype:in64

In [17]:
df.Name

0      Alice
1        Bob
2    Charlie
Name: Name, dtype: object

In [19]:
df["Senior"] = df.Age > 33
print(df)


      Name  Age           City  Senior
0    Alice   25       New York   False
1      Bob   30  San Francisco   False
2  Charlie   35    Los Angeles    True


matplotib.pyplot as plt

In [26]:
# sample data
x = [10, 20, 30, 40, 50]
y = [20, 40, 60, 80, 100]


In [ ]:
plt.plot(x, y)
plt.xlabel('X-axis')
plt.ylabel('Y-axis')
plt.title('Sample Plot')
plt.grid(True)
plt.show()

In [ ]:
plt.figure(figsize=(8, 6))
plt.bar(x, y)
plt.xlabel('X-axis')
plt.ylabel('Y-axis')
plt.title('Sample Bar Plot')
plt.grid(True)
plt.show()

In [ ]:
plt.figure(figsize=(8, 6))
plt.scatter(x, y)
plt.xlabel('X-axis')
plt.ylabel('Y-axis')
plt.title('Sample Scatter Plot')
plt.grid(True)
plt.show()

In [34]:
# Histogram
data = [1, 2, 2, 3, 3, 3, 4, 4, 5]

In [ ]:
plt.figure(figsize=(8, 6))
sus = plt.hist(data, bins=5)
plt.xlabel('Value')
plt.ylabel('Frequency')
plt.title('Sample Histogram')
plt.grid(True)
plt.show()

In [35]:
df.columns.to_list()

['Name', 'Age', 'City', 'Senior']